#!/usr/bin/env node
// scripts/build.js
"use strict";

const fs   = require("fs");
const path = require("path");

const SRC  = path.join(__dirname, "../src/index.js");
const DIST = path.join(__dirname, "../dist");

if (!fs.existsSync(DIST)) fs.mkdirSync(DIST);

// 1. CJS
fs.copyFileSync(SRC, path.join(DIST, "index.js"));
console.log("✅  dist/index.js      (CommonJS)");

// 2. ESM
const cjs = fs.readFileSync(SRC, "utf-8");
const esm = cjs
  .replace(/^"use strict";\n\n/, "")
  .replace(/const fs\s*=\s*require\("fs"\);/,    'import fs from "fs";')
  .replace(/const path\s*=\s*require\("path"\);/, 'import path from "path";')
  .replace(
    /module\.exports\s*=\s*\{([\s\S]*?)\};?\s*$/,
    function(_, body) {
      var names = body.split(",").map(function(s) { return s.trim(); }).filter(Boolean);
      return "export {\n" + names.map(function(n) { return "  " + n; }).join(",\n") + "\n};\n";
    }
  );
fs.writeFileSync(path.join(DIST, "index.mjs"), esm, "utf-8");
console.log("✅  dist/index.mjs     (ES Module)");

// 3. TypeScript definitions
var lines = [
  "// Type definitions for kq-config",
  "// Auto-generated by scripts/build.js",
  "",
  'export type KQRole = "server" | "client" | string;',
  "",
  "export type KQSchemaRule = {",
  '  type?: "string" | "number" | "boolean";',
  "  required?: boolean;",
  "  default?: string | number | boolean | null;",
  "};",
  "",
  "export type KQSchema = Record<string, KQSchemaRule>;",
  "export type KQConfigValue = string | number | boolean | null;",
  "export type KQAllConfig = Record<string, KQConfigValue>;",
  "",
  "export type KQOptions = {",
  "  envFile?: string | false;",
  "};",
  "",
  "export declare class KQParser {",
  "  constructor(",
  "    filepath: string,",
  "    role: KQRole,",
  "    overrideFile?: string | null,",
  "    options?: KQOptions",
  "  );",
  "  readonly role: string;",
  "  readonly filepath: string;",
  "  readonly loaded: boolean;",
  "  load(): this;",
  "  validate(schema: KQSchema): this;",
  "  get(key: string, fallback?: KQConfigValue): KQConfigValue;",
  "  has(key: string): boolean;",
  "  all(): KQAllConfig;",
  "  keys(): string[];",
  "}",
  "",
  "export declare class KQError extends Error {",
  '  name: "KQError";',
  "}",
  "export declare class KQValidationError extends KQError {",
  '  name: "KQValidationError";',
  "}",
  "export declare class KQFileNotFoundError extends KQError {",
  '  name: "KQFileNotFoundError";',
  "  filepath: string;",
  "}",
  "export declare class KQEnvError extends KQError {",
  '  name: "KQEnvError";',
  "  varName: string;",
  "}",
  ""
];

fs.writeFileSync(path.join(DIST, "index.d.ts"), lines.join("\n"), "utf-8");
console.log("✅  dist/index.d.ts    (TypeScript)");
console.log("\n🎉  Build complete → dist/");