#!/usr/bin/env node
// scripts/build.js
// Generates dist/index.js (CJS), dist/index.mjs (ESM), dist/index.d.ts (TypeScript)

"use strict";

const fs   = require("fs");
const path = require("path");

const SRC  = path.join(__dirname, "../src/index.js");
const DIST = path.join(__dirname, "../dist");

if (!fs.existsSync(DIST)) fs.mkdirSync(DIST);

// ── 1. CJS — copy src directly ──────────────────────────────────────
fs.copyFileSync(SRC, path.join(DIST, "index.js"));
console.log("✅  dist/index.js      (CommonJS)");

// ── 2. ESM — rewrite require/module.exports to import/export ────────
const cjs = fs.readFileSync(SRC, "utf-8");

const esm = cjs
  // Remove "use strict" (ESM is strict by default)
  .replace(/^"use strict";\n\n/, "")
  // require("fs") → import fs from "fs"
  .replace(/const fs\s*=\s*require\("fs"\);/,   'import fs from "fs";')
  // require("path") → import path from "path"
  .replace(/const path\s*=\s*require\("path"\);/, 'import path from "path";')
  // module.exports = { ... } → export { ... }
  .replace(
    /module\.exports\s*=\s*\{([\s\S]*?)\};?\s*$/,
    (_, body) => {
      const names = body.split(",").map(s => s.trim()).filter(Boolean);
      return `export {\n${names.map(n => `  ${n}`).join(",\n")}\n};\n`;
    }
  );

fs.writeFileSync(path.join(DIST, "index.mjs"), esm, "utf-8");
console.log("✅  dist/index.mjs     (ES Module)");

// ── 3. TypeScript type definitions ──────────────────────────────────
const dts = `// Type definitions for kq-config
// Auto-generated by scripts/build.js

export type KQRole = "server" | "client" | string;

export type KQSchemaRule = {
  /** Expected JavaScript typeof string: "string" | "number" | "boolean" */
  type?: "string" | "number" | "boolean";
  /** If true, validation throws when the key is missing */
  required?: boolean;
  /** Applied when key is missing and required is false */
  default?: string | number | boolean | null;
};

export type KQSchema = Record<string, KQSchemaRule>;

export type KQConfigValue = string | number | boolean | null;

export type KQAllConfig = Record<string, KQConfigValue>;

/**
 * Parses a .kq config file and returns values for a specific role.
 *
 * @example
 * \`\`\`ts
 * import { KQParser } from "kq-config";
 *
 * const server = new KQParser("config.kq", "server")
 *   .load()
 *   .validate({ port: { type: "number", required: true } });
 *
 * const port = server.get("port"); // number | string | boolean | null
 * \`\`\`
 */
export declare class KQParser {
  constructor(filepath: string, role: KQRole, overrideFile?: string | null);

  /** The role this parser was created for */
  readonly role: string;

  /** The resolved filepath */
  readonly filepath: string;

  /** Whether .load() has been called */
  readonly loaded: boolean;

  /**
   * Load and merge all config layers.
   * Must be called before get(), has(), all(), validate().
   */
  load(): this;

  /**
   * Validate the loaded config against a schema.
   * Applies defaults for optional missing keys.
   * Throws KQValidationError if required keys are missing or types mismatch.
   */
  validate(schema: KQSchema): this;

  /** Get a single config value, with optional fallback */
  get(key: string, fallback?: KQConfigValue): KQConfigValue;

  /** Check if a key exists */
  has(key: string): boolean;

  /** Return all config values as a plain object */
  all(): KQAllConfig;

  /** Return all config keys */
  keys(): string[];
}

/** Base error class for all kq-config errors */
export declare class KQError extends Error {
  name: "KQError";
}

/** Thrown when schema validation fails */
export declare class KQValidationError extends KQError {
  name: "KQValidationError";
}

/** Thrown when a config file is not found */
export declare class KQFileNotFoundError extends KQError {
  name: "KQFileNotFoundError";
  filepath: string;
}

/** Thrown when a required \$ENV: variable is not set */
export declare class KQEnvError extends KQError {
  name: "KQEnvError";
  varName: string;
}
`;

fs.writeFileSync(path.join(DIST, "index.d.ts"), dts, "utf-8");
console.log("✅  dist/index.d.ts    (TypeScript)");

console.log("\n🎉  Build complete → dist/");
